// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3d4IzqzXNcH9od4nS6-BaIAXgOD-B4Hc',
    appId: '1:248536647153:web:2218b7f9a98105cab6f050',
    messagingSenderId: '248536647153',
    projectId: 'studentmanagement-99159',
    authDomain: 'studentmanagement-99159.firebaseapp.com',
    storageBucket: 'studentmanagement-99159.appspot.com',
    measurementId: 'G-L4LM6ZTZDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtUvWGnXaCL__ryfFhhy0ml1UbX0qPqQI',
    appId: '1:248536647153:android:1c8a649a6f4c8d03b6f050',
    messagingSenderId: '248536647153',
    projectId: 'studentmanagement-99159',
    storageBucket: 'studentmanagement-99159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqbxlQz9Bq4co0kow1QzyiZ48pJcTby_A',
    appId: '1:248536647153:ios:5c1efd8fdc318f2bb6f050',
    messagingSenderId: '248536647153',
    projectId: 'studentmanagement-99159',
    storageBucket: 'studentmanagement-99159.appspot.com',
    iosBundleId: 'com.example.stdManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqbxlQz9Bq4co0kow1QzyiZ48pJcTby_A',
    appId: '1:248536647153:ios:5c1efd8fdc318f2bb6f050',
    messagingSenderId: '248536647153',
    projectId: 'studentmanagement-99159',
    storageBucket: 'studentmanagement-99159.appspot.com',
    iosBundleId: 'com.example.stdManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3d4IzqzXNcH9od4nS6-BaIAXgOD-B4Hc',
    appId: '1:248536647153:web:cccbc2cde7b3e1c6b6f050',
    messagingSenderId: '248536647153',
    projectId: 'studentmanagement-99159',
    authDomain: 'studentmanagement-99159.firebaseapp.com',
    storageBucket: 'studentmanagement-99159.appspot.com',
    measurementId: 'G-VGF1NQQZE4',
  );

}